/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SongsIndexImport } from './routes/songs/index'
import { Route as PeopleIndexImport } from './routes/people/index'
import { Route as MoviesIndexImport } from './routes/movies/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SongsIndexRoute = SongsIndexImport.update({
  path: '/songs/',
  getParentRoute: () => rootRoute,
} as any)

const PeopleIndexRoute = PeopleIndexImport.update({
  path: '/people/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesIndexRoute = MoviesIndexImport.update({
  path: '/movies/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexImport
      parentRoute: typeof rootRoute
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleIndexImport
      parentRoute: typeof rootRoute
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies': typeof MoviesIndexRoute
  '/people': typeof PeopleIndexRoute
  '/songs': typeof SongsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies': typeof MoviesIndexRoute
  '/people': typeof PeopleIndexRoute
  '/songs': typeof SongsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/songs/': typeof SongsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movies' | '/people' | '/songs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movies' | '/people' | '/songs'
  id: '__root__' | '/' | '/movies/' | '/people/' | '/songs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/movies/",
        "/people/",
        "/songs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/movies/": {
      "filePath": "movies/index.tsx"
    },
    "/people/": {
      "filePath": "people/index.tsx"
    },
    "/songs/": {
      "filePath": "songs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
